ğŸ“©yaada
â“Gaaffii Qabdan mara asirratti 
Nuuf barreesaa.ğŸ‘‡ğŸ‘‡ğŸ‘‡ğŸ‘‡ğŸ‘‡Â Â Â Â Â Â Â Â Â Â Â Â Â Â  ğŸ‘‡ğŸ‘‡ğŸ‘‡ğŸ‘‡ğŸ‘‡ğŸ‘‡ğŸ‘‡ğŸ‘‡ğŸ‘‡ğŸ‘‡ğŸ‘‡
Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â Â  @Abdureman_bot

Galata guddaa nu biraa qabduğŸ‘
@) SABAA KOOF
@) SABAA KOOF 
@) SABAA KOOF
